### ISSUE TITLE
Exception when creating mapper for generic type

### ISSUE THREAD

**Issue by michalrrcc** [remondis-it/remap#116]
When creating a mapper for generic type like this:
```
MyType<R> {
      R getResult();
}
```
in remap 4.2.0 the following exception is thrown:
```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.remondis.remap.GenericParameterContext.init(GenericParameterContext.java:46)
	at com.remondis.remap.GenericParameterContext.<init>(GenericParameterContext.java:29)
	at com.remondis.remap.ReassignTransformation.validateTransformation(ReassignTransformation.java:182)
	at com.remondis.remap.MappingConfiguration.validateMapping(MappingConfiguration.java:444)
	at com.remondis.remap.MappingConfiguration.mapper(MappingConfiguration.java:365)
```
It is working without problems in remap 4.1.12

**Comment by schuettec** [comment]
Thanks, I will have a look at this.

**Comment by schuettec** [comment]
#117 is in pipeline to fix that.

**Comment by schuettec** [comment]
ReMap 4.2.1 is on its way to Maven Central. Let me know if that fixes your problem.

Thanks for the bug report!

**Comment by michalrrcc** [comment]
The new version works, thanks for the super fast fix!
