### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by sebasira** [remondis-it/remap#134]
Hi! I'm using this to map my Entities and DTOs in the server side.

I'd like to do the same in my Android app.

I've written the code, and test for it all pass. But when I run the app I get this exception:

```
Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
```

Looking over the internet I get to [this StackOverflow answer](https://stackoverflow.com/a/61570006/2597775).

Could you please provide a way to make it work on Android?

Thanks!

**Comment by sebasira** [comment]
I've also found [this](https://www.nuomiphp.com/eplan/en/266259.html), that could help to identify the problem.

**Comment by schuettec** [comment]
Hm, seems like there is a problem when reMap tries to create proxy classes.

The stackoverflow article does not give any hope that it is possible to
create dynamic proxy classes under android.

To understand the problem better, would you please provide a little more of
the stacktrace?

I will let you know if I can do something to make it work.

Thanks!

Sebastian M. Irazabal <notifications@github.com> schrieb am Mi., 7. Okt.
2020, 15:24:

**Comment by sebasira** [comment]
Of Course! This is the full stacktrace:

```
2020-10-07 10:10:50.880 4548-4548/ar.com.siid.telemetricprivate.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ar.com.siid.telemetricprivate.debug, PID: 4548
    java.lang.ExceptionInInitializerError
        at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:30)
        at com.remondis.remap.MappingConfiguration.getPropertyFromFieldSelector(MappingConfiguration.java:538)
        at com.remondis.remap.MappingConfiguration.reassign(MappingConfiguration.java:228)
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:27)
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42)
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
        at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:30) 
        at com.remondis.remap.MappingConfiguration.getPropertyFromFieldSelector(MappingConfiguration.java:538) 
        at com.remondis.remap.MappingConfiguration.reassign(MappingConfiguration.java:228) 
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:27) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:452)
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:334)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) 
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) 
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) 
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) 
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) 
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) 
        at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:30) 
        at com.remondis.remap.MappingConfiguration.getPropertyFromFieldSelector(MappingConfiguration.java:538) 
        at com.remondis.remap.MappingConfiguration.reassign(MappingConfiguration.java:228) 
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:27) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
        at java.lang.reflect.Method.invoke(Native Method) 
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459) 
        at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:452) 
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:334) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) 
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) 
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) 
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) 
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) 
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) 
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) 
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) 
        at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:30) 
        at com.remondis.remap.MappingConfiguration.getPropertyFromFieldSelector(MappingConfiguration.java:538) 
        at com.remondis.remap.MappingConfiguration.reassign(MappingConfiguration.java:228) 
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:27) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

This is my mapper:

```java
1. readToCreate = Mapping.from(UsuarioProfile_readDTO.class)
2.                 .to(UsuarioProfile_createDTO.class)
3.                 .useMapper(docTypeMapper.fromDocType)
4.                 .reassign(UsuarioProfile_readDTO::getDocType)
5.                     .to(UsuarioProfile_createDTO::getDocTypeValue)
6.                 .mapper();
```

The stacktrace signal that the problem ocurrs at `UsuarioProfileMapper.java:27` (which will be line **4.** in the snippet above)

So I try another mapper without the **reassign**, like this:

```java
1. readToCreate = Mapping.from(UsuarioProfile_readDTO.class)
2.                 .to(UsuarioProfile_createDTO.class)
3.                 .useMapper(docTypeMapper.fromDocType)
4.                 .mapper();
```

And this time the failure was another one, with this other stacktrace:


```
2020-10-07 12:09:29.332 8241-8241/ar.com.siid.telemetricprivate.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ar.com.siid.telemetricprivate.debug, PID: 8241
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
        at com.remondis.remap.Properties.getProperties(Properties.java:114)
        at com.remondis.remap.MappingConfiguration.getUnmappedProperties(MappingConfiguration.java:483)
        at com.remondis.remap.MappingConfiguration.getUnmappedDestinationProperties(MappingConfiguration.java:465)
        at com.remondis.remap.MappingConfiguration.addStrictMapping(MappingConfiguration.java:405)
        at com.remondis.remap.MappingConfiguration.mapper(MappingConfiguration.java:361)
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:29)
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42)
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Introspector" on path: DexPathList[[zip file "/data/app/ar.com.siid.telemetricprivate.debug-KcUN_8ygX8Gi2cK-Y3A4bw==/base.apk"],nativeLibraryDirectories=[/data/app/ar.com.siid.telemetricprivate.debug-KcUN_8ygX8Gi2cK-Y3A4bw==/lib/x86, /data/app/ar.com.siid.telemetricprivate.debug-KcUN_8ygX8Gi2cK-Y3A4bw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.remondis.remap.Properties.getProperties(Properties.java:114) 
        at com.remondis.remap.MappingConfiguration.getUnmappedProperties(MappingConfiguration.java:483) 
        at com.remondis.remap.MappingConfiguration.getUnmappedDestinationProperties(MappingConfiguration.java:465) 
        at com.remondis.remap.MappingConfiguration.addStrictMapping(MappingConfiguration.java:405) 
        at com.remondis.remap.MappingConfiguration.mapper(MappingConfiguration.java:361) 
        at ar.com.siid.telemetricprivate.converter.UsuarioProfileMapper.<init>(UsuarioProfileMapper.java:29) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoPresenter.<init>(PersonalInfoPresenter.java:42) 
        at ar.com.siid.telemetricprivate.feature.profile.personalinfo.PersonalInfoActivity.onCreate(PersonalInfoActivity.java:96) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

This time the error is at line **4** of the second snippet.

If you need me to perform more test I'll be glad to help.

Thank you very much!

**Comment by sebasira** [comment]
I'm sorry I do not know much about proxies and ClassLoader but after searching for:

> create dynamic proxy classes under android

I've found [this](https://developer.android.com/reference/java/lang/reflect/Proxy) from the Official Android Developer Docs. 

I hope you find it useful!

**Comment by sebasira** [comment]
Hi! I'm sorry to bother you again. Did you have a chance to look into this? 

If I could assist you in any way let me know

Thank you!

**Comment by schuettec** [comment]
Hi, I did a little research. I think it's not an easy task to make ReMap compatible on Android. The problem is the cglib dependency and the runtime byte code generation.
I did a little experimental work on this, but another problem is, that I cannot test the results, since I cannot test & check ReMap running in an Android environment in the build pipeline.

I'm sorry - I can't get you a quick solution.

Would you like to provide an PR? :)

**Comment by sebasira** [comment]
Hi! Thank you for your time.

I've been doing some research since your answer and indeed find that the issue is related to the Dalvik VM used by Android.

The problem is that Android does not have full **java.beans** package and that's why the `ClassNotFoundException` is thrown.

Looking into it, the alternatives are:

1-  Use [openbeans](https://code.google.com/archive/p/openbeans/) to replace **java.beans** dependencies
2- Use [ByteBuddy](https://bytebuddy.net/#/)

I think the simpler one would be **1**

I've make a test an make it work in Android. I'll provide a PR

**Comment by sebasira** [comment]
Just to keep posted anyone looking into this, after the successful test (in the previous PR) I've notice that the problem is more complex than it seems and it's not only about the **java.beans** package but also some dependencies from CGLIB as @schuettec pointed out.

I've create a more complex test and it was failing. And as said before is due to Android using DexClassLoader (Dalvivk VM) and no the JVM.

So my fork is not Android-compatible.

**Comment by schuettec** [comment]
Hi, I'm sorry to hear that. But there might be another option for you. I stubled upon a project "CGLIB For Android". It provides the class `Enhancer` which is the only thing ReMap depends on (https://github.com/leo-ouyang/CGLib-for-Android). So I you want to spend further time on this one, you could try to get things working with this version of cglib.

**Comment by sebasira** [comment]
Thanks I'll try it out... 

I also found out that Android does not have the full **javax** package, so there's no `Transform` (from package  *javax.xml. crypto.dsig.Transform*)

I seems more complex than what I initially thought!
