### ISSUE TITLE
Suggestion to use an instantiated objet as "from"

### ISSUE THREAD

**Issue by mmaryo** [remondis-it/remap#37]
Hello

I have an suggestion because sometime I populate an object that exists before (loaded from database for update operations for exemple)

    private static final Mapper<SfContact, CustomerEntity> mapperToEntity =
            Mapping.from(SfContact.class)
                    .to(CustomerEntity.class)
                    .mapper();

    public static CustomerEntity toEntity(CustomerEntity entity, SfContact sfContact) {
        return mapperToEntity.map(sfContact);  <-----
    }

I would like to have someting like : 

    return mapperToEntity.with(entity).map(sfContact); 

or (update)

    return mapperToEntity.map(entity, sfContact); 

What do you think about it ?

**Comment by schuettec** [comment]
Correct me if I got that wrong: Is your purpose to overwrite field values of the entity instance with field values of `sfContact` according to the mapping configuration?

**Comment by mmaryo** [comment]
yes 

exemple : 

CustomerEntity
id: 1
name: toto
email: toto@example.com
createdDate: 2018-04-20

SfContact
name: john
email: john@google.com

so result is : 
CustomerEntity
id: 1
name: john
email: john@google.com
createdDate: 2018-04-20

**Comment by mmaryo** [comment]
Something like ?


Mapping.java

    D map(S source, D destination) {
        if (source == null) {
            throw MappingException.denyMappingOfNull();
        }
        for (Transformation t : mappings) {
            t.performTransformation(source, destination);
        }
        return destination;
    }

**Comment by schuettec** [comment]
Yes, I thought about that, but when we designed ReMap, we decided to not implement that. The reason had something to do with testability, but I do not see any problems because the only thing we would change is the way the target object is passed to the transformations.

I definitely see the use case.

**Comment by schuettec** [comment]
There is one thing that is unclear for me: The parent instance can be passed into the method you suggested but ReMap would create the instances for nested mappings itself. When using the suggested feature, would you expect this behaviour or would you expect that the nested mappings will also use the specified destination object if there is one?

**Comment by mmaryo** [comment]
I write the code and test and will pull it tonight :)

**Comment by schuettec** [comment]
The Code is ready but the design is unclear for me. What do you think about the problems mentioned above?

**Comment by schuettec** [comment]
This is my implementation of your suggested feature https://github.com/remondis-it/remap/pull/38.
You may try it out ;)

**Comment by mmaryo** [comment]
I do a pull request :)
what do you think ?
https://github.com/remondis-it/remap/pull/39

**Comment by schuettec** [comment]
Thanks for your support! Looks quite good to me, but the build failed. You may want to check out this https://github.com/remondis-it/remap/blob/develop/CONTRIBUTE.md.

And you missed a test case: You modified the `ReassingTransformation` to support passing the destination instance. I would like to have a test for this use case to be sure everything works as expected.

**Comment by mmaryo** [comment]
ok ! it's done

**Comment by schuettec** [comment]
I'm sorry but it seems I have to revert your changes. The test I mentioned was not implemented, but I thought so. I build a mapping that produces an error. Please have a look at `com.remondis.remap.mapInto.MapperTest` in https://github.com/remondis-it/remap/pull/42.

The problem is, that `com.remondis.remap.ReassignTransformation.convertCollection(...)` now needs to iterate over both, the source and the destination list (possibly in the right order) to do the nested mapping with overwrite-strategy. Currently the field access is broken with your implementation:

```
com.remondis.remap.MappingException: Invoking access method for property java.beans.PropertyDescriptor[name=city; propertyType=class java.lang.String; readMethod=public java.lang.String com.remondis.remap.mapInto.Address.getCity(); writeMethod=public void com.remondis.remap.mapInto.Address.setCity(java.lang.String)] failed.
	at com.remondis.remap.MappingException.invocationFailed(MappingException.java:98)
	at com.remondis.remap.Transformation.writeOrFail(Transformation.java:112)
	at com.remondis.remap.ReassignTransformation.performTransformation(ReassignTransformation.java:51)
	at com.remondis.remap.Transformation.performTransformation(Transformation.java:124)
	at com.remondis.remap.ReassignTransformation.performTransformation(ReassignTransformation.java:1)
	at com.remondis.remap.MapTransformation.performTransformation(MapTransformation.java:1)
	at com.remondis.remap.Mapping.map(Mapping.java:519)
	at com.remondis.remap.Mapper.map(Mapper.java:51)
	at com.remondis.remap.ReassignTransformation.convertValue(ReassignTransformation.java:83)
	at com.remondis.remap.ReassignTransformation.lambda$0(ReassignTransformation.java:67)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.remondis.remap.ReassignTransformation.convertCollection(ReassignTransformation.java:70)
	at com.remondis.remap.ReassignTransformation.performTransformation(ReassignTransformation.java:46)
	at com.remondis.remap.Transformation.performTransformation(Transformation.java:124)
	at com.remondis.remap.ReassignTransformation.performTransformation(ReassignTransformation.java:1)
	at com.remondis.remap.MapTransformation.performTransformation(MapTransformation.java:1)
	at com.remondis.remap.Mapping.map(Mapping.java:519)
	at com.remondis.remap.Mapper.map(Mapper.java:51)
	at com.remondis.remap.mapInto.MapperTest.shouldUseDestinationObjectForNestedMappingsAlso(MapperTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.remondis.remap.Transformation.writeOrFail(Transformation.java:108)
	... 46 more


```

**Comment by mmaryo** [comment]
:/

**Comment by mmaryo** [comment]
have you an idea ?

**Comment by schuettec** [comment]
Yes, this is the problem I mentioned above. My idea was to only provide this feature for the parent instance and document that clearly. Otherwise we have to define what is happening when merging lists and I don't know if that is possible without introducing some kind of non-determinism.

**Comment by mmaryo** [comment]
I found a solution 
I simply disable this feature for collections 
https://github.com/remondis-it/remap/pull/44
what do you think ?

**Comment by schuettec** [comment]
Yes, that seems to be a nice solution. Thank you! 

I will have a closer look tomorrow just to be sure I'm not missing something.

**Comment by mmaryo** [comment]
thank you too
will you do an release soon ? I'm a user of the feature in my company :)

**Comment by schuettec** [comment]
#44 is merged now. There is another pull request in the pipeline. I updated that with your changes and I will try to get that ready for the release 3.0.5. If everything works I will do the release in a few minutes. Note that Maven Central need its time to sync the new release.

**Comment by mmaryo** [comment]
thanks !!

**Comment by schuettec** [comment]
The other suggestion #45 requires some migrations when read-only properties were used with an earlier version of ReMap. Therefore the version 4.0.0 was chosen for the next release. Your feature will be released in this version.

The Maven Central sync was started! 

Thanks for your contribution!
