### ISSUE TITLE
[JDK 10] Caused by: java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by ghost** [remondis-it/remap#56]
Hi,
Is the latest version of mapper compatible with JDK 10?
Just bumped my project and can see this exception caused by Remap.

> Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160) ~[asm-6.0.jar:6.0]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143) ~[asm-6.0.jar:6.0]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418) ~[asm-6.0.jar:6.0]
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:69) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1132) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:630) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[cglib-3.2.6.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480) ~[cglib-3.2.6.jar:na]
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305) ~[cglib-3.2.6.jar:na]
	at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:54) ~[remap-4.0.0.jar:na]
	at com.remondis.remap.Mapping.getTypedPropertyFromFieldSelector(Mapping.java:353) ~[remap-4.0.0.jar:na]
	at com.remondis.remap.Mapping.reassign(Mapping.java:157) ~[remap-4.0.0.jar:na]

Thanks

**Comment by ghost** [comment]
Ok, I had to bump asm version to > 6.1 that is compatible with Java 10
