### ISSUE TITLE
java.lang.NoClassDefFoundError: org/objectweb/asm/Type

### ISSUE THREAD

**Issue by mmaryo** [remondis-it/remap#71]
Hello 

With OpenJDK 11
Remap 4.0.2

When I run my application I have this error : 

2018-11-05 11:24:12,255 WARN  [main] [] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.log | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'productController': Unsatisfied dependency expressed through field 'productMapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productMapper' defined in file [/home/mario/dev/product/product-app/target/classes/fr/app/product/mapper/ProductMapper.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [fr.app.product.mapper.ProductMapper]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/objectweb/asm/Type

An idea ?

**Comment by schuettec** [comment]
Did you have a look at https://github.com/remondis-it/remap/issues/60. There were no further information or reactions about your issue so I closed it but it seems to be the same?

**Comment by mmaryo** [comment]
oh sorry I forget past issue
this is the same

**Comment by schuettec** [comment]
Please checkout this paragraph from the Readme even though you are not using Spring Boot:

https://github.com/remondis-it/remap#spring-boot-issue

This could solve the issue - if you need further assistance let me know.

**Comment by mmaryo** [comment]
sorry I forget the past issue
this is the same error but not the good solution 
I'm using last spring boot with spring framework 5

**Comment by schuettec** [comment]
Hm. Please check your dependency hierarchy and look out for the asm and cglib versions in your output. Maybe the version of asm is overwritten.

You can also try to add the following dependency explicitly to your project:
```
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib</artifactId>
            <version>3.2.9</version>
            <scope>compile</scope>
        </dependency>
```
This will upgrade to the latest version of cglib and asm. 

Since you are running with OpenJDK 11 I think the new asm version is required for your project.

You may also checkout and build https://github.com/remondis-it/remap/pull/73. I upgraded the library in this Pull Request. You can check if that solves the problem.

**Comment by mmaryo** [comment]
with cglib dependency it's work !

**Comment by schuettec** [comment]
Good to hear. In this case the next release will fix this. I'm going to
release this tomorrow.

**Comment by schuettec** [comment]
Target version for the fix is 4.1.1 and it's on its way to Maven Central.

**Comment by mmaryo** [comment]
thanks 
I need it :)

**Comment by mmaryo** [comment]
It's not works :/


	    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productItemMapper' defined in file [/home/mario/dev/mmh/vishnou/seth-business/seth-business-order/target/classes/fr/app/seth/order/converter/ProductItemMapper.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [fr.app.seth.order.converter.ProductItemMapper]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1228)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
		at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
		... 86 common frames omitted
	Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [fr.app.seth.order.converter.ProductItemMapper]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1220)
		... 98 common frames omitted
	Caused by: java.lang.ExceptionInInitializerError: null
		at com.remondis.remap.InvocationSensor.<init>(InvocationSensor.java:30)
		at com.remondis.remap.Mapping.getPropertyFromFieldSelector(Mapping.java:424)
		at com.remondis.remap.Mapping.omitInDestination(Mapping.java:112)
		at fr.app.seth.order.converter.ProductItemMapper.<init>(ProductItemMapper.java:29)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
		... 100 common frames omitted
	Caused by: java.lang.IllegalArgumentException: null
		at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:75)
		at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49)
		at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
		at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
		at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
		at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
		at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
		at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
		at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
		at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
		at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
		at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
		at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
		at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
		at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
		... 109 common frames omitted

	Process finished with exit code 1

**Comment by schuettec** [comment]
Can you please provide the dependency tree of your project? An excerpt that
shows remap dependency and the transitive dependencies of it?
And I need to know which version of ```net.minidev:accessors-smart``` is in your dependency hierarchy!

**Comment by mmaryo** [comment]
in dependency tree : net.minidev:accessors-smart:jar:1.2:test


And finally I found solution : 


            <dependency>
                <groupId>com.remondis</groupId>
                <artifactId>remap</artifactId>
                <version>4.1.1</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>7.0</version>
            </dependency>

**Comment by schuettec** [comment]
Yes that is a workaround. I just realized that I made a mistake. ReMap currently does not depend on ASM 7.0. I will fix that!

Thank you!

**Comment by schuettec** [comment]
> ReMap currently does not depend on ASM 7.0.

Sorry I was wrong. The version 4.1.1 of ReMap actually depends on ASM 7.0. So everything should be fine. I cannot reproduce any problems.

**Comment by mmaryo** [comment]
Ok thanks 
It works for me with this workaround so it's ok

**Comment by schuettec** [comment]
Ok. Then I will close this issue.
